# Generated by Django 5.1.4 on 2025-02-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('titulo_topico_um', models.CharField(max_length=50, verbose_name='Título Tópico 1')),
                ('topico_um', models.TextField(verbose_name='Tópico 1')),
                ('titulo_topico_dois', models.CharField(max_length=50, verbose_name='Título Tópico 2')),
                ('topico_dois', models.TextField(verbose_name='Tópico 2')),
                ('titulo_topico_tres', models.CharField(max_length=50, verbose_name='Título Tópico 3')),
                ('topico_tres', models.TextField(verbose_name='Tópico 3')),
            ],
        ),
    ]
