# Generated by Django 5.1.4 on 2025-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Página Inicial', 'verbose_name_plural': 'Páginas Iniciais'},
        ),
        migrations.AddField(
            model_name='home',
            name='rodape',
            field=models.TextField(default='Texto padrao para rodape', max_length=10, verbose_name='Rodape'),
        ),
    ]
